CC = gfortran

CFLAGS = -Werror -Wall

1:
	$(CC) -o exercise_1 ./exercise_1.f90 $(CFLAGS)

2-1:
	$(CC) -o exercise_2_1 ./exercise_2_1.f90 $(CFLAGS)

2-2:
	$(CC) -o exercise_2_2 ./exercise_2_2.f90 $(CFLAGS)
